# Конфигурация для сборки и запуска сервера и клиента.
services:
  auth-server:
    container_name: 'auth-server'
    build:
      context: 'web-auth-server'
      dockerfile: 'Dockerfile'
    ports:
      - '8080:8080'
    depends_on:
      - 'database'
    environment:
      DATASOURCE_DATABASE: 'web-chat'
      DATASOURCE_HOST: 'database'
      DATASOURCE_PORT: '3306'
      DATASOURCE_USER: 'arkham'
      DATASOURCE_PASSWORD: 'secret'
    networks:
      - 'inner'
      - 'outer'

  server:
    container_name: 'server'
    build:
      context: 'web-chat-server'
      dockerfile: 'Dockerfile'
    ports:
      - '8081:8081'
    depends_on:
      - 'database'
    environment:
      DATASOURCE_DATABASE: 'web-chat'
      DATASOURCE_HOST: 'database'
      DATASOURCE_PORT: '3306'
      DATASOURCE_USER: 'arkham'
      DATASOURCE_PASSWORD: 'secret'
    networks:
      - 'inner'
      - 'outer'

  client:
    container_name: 'client'
    build:
      context: 'web-chat-client'
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'
    depends_on:
      - 'auth-server'
      - 'server'
    networks:
      - 'outer'

  database:
    container_name: 'database'
    image: 'mariadb:latest'
    restart: 'always'
    environment:
      MARIADB_DATABASE: 'web-chat'
      MARIADB_PASSWORD: 'secret'
      MARIADB_ROOT_PASSWORD: 'verysecret'
      MARIADB_USER: 'arkham'
    ports:
      - '3306:3306'
    volumes:
      - 'data:/var/lib/mysql'
    networks:
      - 'inner'

volumes:
  data:

networks:
  inner:
  outer:
